const hashtagsAPI = [
  {
    id: 1,
    letter: "A",
    hashtags: [
      "#Amazing",
      "#Adventure",
      "#Artistic",
      "#Aspire",
      "#Authentic",
      "#Achieve",
      "#Aesthetic",
      "#Active",
      "#Aggressive",
      "#Admire",
      "#Amazing",
      "#Adventure",
      "#Artistic",
      "#Aspire",
      "#Authentic",
      "#Achieve",
      "#Aesthetic",
      "#Active",
      "#Aggressive",
      "#Admire",
      "#AOL",
      "#Avatar",
      "#Anime",
      "#Action",
      "#Artist",
      "#Astrology",
      "#Album",
      "#America",
      "#Airwaves",
      "#Antivirus",
      "#Avenue",
      "#Animation",
      "#Alumni",
      "#Applause",
      "#Apple",
      "#Aspirations",
      "#Athletes",
      "#Affection",
      "#Albums",
      "#Awareness",
      "#Alone",
      "#Accomplishments",
      "#Angels",
      "#Anthem",
      "#Astonishing",
      "#Absolute",
      "#Adventures",
      "#Anticipation",
      "#Activity",
      "#Appreciation",
      "#Actionable",
      "#Achievement",
      "#Advancement",
      "#Access",
      "#Ambition",
      "#Acceleration",
      "#Adrenaline",
      "#Alliance",
      "#Allegiance",
      "#Attraction",
      "#Authenticity",
      "#Awe",
      "#Altruism",
      "#Abundance",
      "#Adversity",
      "#Alleviation",
      "#Analyzation",
      "#Appeal",
      "#Agility",
      "#Awaken",
      "#Ascension",
      "#Anticipate",
      "#Alluring",
      "#Admiration",
      "#Arousal",
      "#Aptitude",
      "#Awakening",
      "#Allegory",
      "#Artistry",
      "#Aggrandizement",
      "#Alteration",
      "#Advocate",
      "#Arise",
      "#Ardor",
      "#Ascertain",
      "#Acceptance",
      "#Ambience",
      "#Appealing",
      "#Addiction",
      "#Agitation",
      "#Alertness",
      "#Acumen",
      "#Accomplish",
      "#Astonish",
      "#Ablaze",
      "#Astounding",
      "#Alert",
      "#Adoration",
      "#Acquaintance",
      "#Anniversary",
      "#Ascendancy",
      "#Anxiety",
      "#Advocacy",
      "#Accomplished",
      "#Accumulation",
      "#Amusement",
      "#Alleviate",
      "#Annihilation",
      "#Appreciated",
      "#Allowance",
      "#Apocalypse",
      "#Amplify",
      "#Acquiescence",
      "#Alleviating",
      "#Arrive",
      "#Adaptation",
      "#Acrobatics",
      "#Affirmation",
      "#Anchor",
      "#Adaptable",
      "#AchievementUnlocked",
      "#Aggrandize",
      "#Allure",
      "#Automate",
      "#Anticipating",
      "#Acceleration",
      "#AweStruck",
      "#Announce",
      "#Affordability",
      "#Awesomeness",
      "#AmusementPark",
      "#AdventureTime",
      "#Artifact",
      "#Altruistic",
    ],
  },
  {
    id: 2,
    letter: "B",
    hashtags: [
      "#Brilliant",
      "#Bold",
      "#Balanced",
      "#Blessed",
      "#Beauty",
      "#Breathe",
      "#Blissful",
      "#BetterLife",
      "#BusinessGoals",
      "#Believe",
      "#Brilliant",
      "#Balance",
      "#Beautiful",
      "#Blessed",
      "#Bold",
      "#Breathe",
      "#Better",
      "#Believe",
      "#Bliss",
      "#Boss",
      "#Brave",
      "#Buddies",
      "#Bright",
      "#Bounty",
      "#Bling",
      "#Biker",
      "#Boom",
      "#BeastMode",
      "#BFF",
      "#Bespoke",
      "#Blogger",
      "#Breezy",
      "#Babies",
      "#BeachVibes",
      "#Blissful",
      "#Bounce",
      "#Barbecue",
      "#BodyGoals",
      "#BigDreams",
      "#Binge",
      "#Basketball",
      "#Beauty",
      "#Bestie",
      "#Backstage",
      "#BestOfTheBest",
      "#BiggestFan",
      "#Badass",
      "#Blessings",
      "#Business",
      "#Books",
      "#Budget",
      "#Ballet",
      "#BirthdayVibes",
      "#BreakingNews",
      "#Blogging",
      "#Baker",
      "#BrightFuture",
      "#BaeGoals",
      "#Breakthrough",
      "#Building",
      "#Bandana",
      "#Brunch",
      "#Biceps",
      "#Brainy",
      "#BlingBling",
      "#Bravery",
      "#Browns",
      "#Benevolent",
      "#BusinessMind",
      "#Baller",
      "#BingeWatch",
      "#BreezyVibes",
      "#BeInspired",
      "#BookLovers",
      "#BiggerGoals",
      "#BohoVibes",
      "#BigMoves",
      "#ByTheBeach",
      "#Batteries",
      "#Bingeable",
      "#BrilliantMind",
      "#BossLady",
      "#Bubbling",
      "#Buddha",
      "#Boo",
      "#BackToBasics",
      "#BreakingBarriers",
      "#Blazing",
      "#Bargain",
      "#BounceBack",
      "#BespokeDesigns",
      "#BetterTogether",
      "#BohemianStyle",
      "#BuildingDreams",
      "#BelieveInYourself",
      "#BeyondTheLimit",
      "#BlessedLife",
      "#BlackAndWhite",
      "#Buzzy",
      "#BubblyPersonality",
      "#BalletLife",
      "#Bizarre",
      "#Boring",
      "#BeachVibesOnly",
      "#BumperSticker",
      "#Ballin",
      "#Breathtaking",
      "#Banana",
      "#BrandNew",
      "#BestEver",
      "#BallerLife",
      "#Bouncers",
      "#Bravest",
      "#Brothers",
      "#BlessedBeyondMeasure",
      "#BohemianVibes",
      "#BookwormLife",
      "#BlingItOn",
      "#BubblingWithJoy",
      "#BeyondTheStars",
      "#BringingTheHeat",
      "#BottlesUp",
      "#BigChallenges",
      "#BunsOfSteel",
      "#BusinessInspiration",
      "#BeautyAddict",
      "#BackOnTrack",
      "#Bam",
    ],
  },
  {
    id: 3,
    letter: "C",
    hashtags: [
      "#Creative",
      "#Confidence",
      "#Chill",
      "#Courage",
      "#ChangeMaker",
      "#Challenge",
      "#Champion",
      "#Culture",
      "#Classy",
      "#Content",
    ],
  },
  {
    id: 4,
    letter: "D",
    hashtags: [
      "#DreamBig",
      "#Driven",
      "#Dynamic",
      "#Determined",
      "#Delightful",
      "#Discover",
      "#DareToDream",
      "#Dazzling",
      "#Design",
      "#Dedication",
    ],
  },
  {
    id: 5,
    letter: "E",
    hashtags: [
      "#Empower",
      "#Enthusiasm",
      "#Exciting",
      "#Energize",
      "#Evolve",
      "#EnjoyLife",
      "#Elegant",
      "#Enlighten",
      "#Entrepreneur",
      "#Experience",
    ],
  },
  {
    id: 6,
    letter: "F",
    hashtags: [
      "#Fearless",
      "#Focused",
      "#Fashionable",
      "#FitLife",
      "#Fabulous",
      "#Freedom",
      "#Future",
      "#Flourish",
      "#FamilyTime",
      "#FollowYourPassion",
    ],
  },
  {
    id: 7,
    letter: "G",
    hashtags: [
      "#Grateful",
      "#Growth",
      "#Goals",
      "#Genuine",
      "#Greatness",
      "#GoodVibes",
      "#Glorious",
      "#Glamour",
      "#Grind",
      "#GoForIt",
    ],
  },
  {
    id: 8,
    letter: "H",
    hashtags: [
      "#Hustle",
      "#Happiness",
      "#Hopeful",
      "#Healing",
      "#HardWork",
      "#HealthyLiving",
      "#Harmony",
      "#Honesty",
      "#HighEnergy",
      "#HelpingHands",
    ],
  },
  {
    id: 9,
    letter: "I",
    hashtags: [
      "#Innovate",
      "#Inspire",
      "#Imagination",
      "#Intuition",
      "#Independence",
      "#Integrity",
      "#Influencer",
      "#Incredible",
      "#InvestInYourself",
      "#Involved",
    ],
  },
  {
    id: 10,
    letter: "J",
    hashtags: [
      "#Journey",
      "#Joyful",
      "#JustDoIt",
      "#JumpStart",
      "#Jovial",
      "#Justice",
      "#JuggleLife",
      "#JokesOnYou",
      "#JoinTheMovement",
      "#JungleVibes",
    ],
  },
  {
    id: 11,
    letter: "K",
    hashtags: [
      "#Kindness",
      "#KeenEye",
      "#KeepItUp",
      "#Karma",
      "#Knowledge",
      "#KissTheSun",
      "#KickingGoals",
      "#KillerInstinct",
      "#KickingIt",
      "#KingVibes",
    ],
  },
  {
    id: 12,
    letter: "L",
    hashtags: [
      "#LiveLaughLove",
      "#Leadership",
      "#Lifestyle",
      "#Legacy",
      "#LoveLife",
      "#LearnAndGrow",
      "#Limitless",
      "#Loyalty",
      "#LifeGoals",
      "#LiftEachOtherUp",
    ],
  },
  {
    id: 13,
    letter: "M",
    hashtags: [
      "#Motivation",
      "#Mindset",
      "#Masterpiece",
      "#MomentOfTheDay",
      "#Manifest",
      "#MoveForward",
      "#MakeItHappen",
      "#Mindfulness",
      "#MusclePower",
      "#MasterYourCraft",
    ],
  },
  {
    id: 14,
    letter: "N",
    hashtags: [
      "#NewBeginnings",
      "#NeverGiveUp",
      "#NoLimits",
      "#Nurture",
      "#NextLevel",
      "#NeverStop",
      "#NatureLover",
      "#NomadLife",
      "#NewChapter",
      "#NobleSoul",
    ],
  },
  {
    id: 15,
    letter: "O",
    hashtags: [
      "#Overcome",
      "#Opportunity",
      "#Optimistic",
      "#Originality",
      "#Outshine",
      "#OpenMind",
      "#OnTop",
      "#Obsessed",
      "#Organized",
      "#OngoingSuccess",
    ],
  },
  {
    id: 16,
    letter: "P",
    hashtags: [
      "#Passion",
      "#PositiveVibes",
      "#Perseverance",
      "#Progress",
      "#PursuitOfHappiness",
      "#Powerful",
      "#PersonalGrowth",
      "#Purpose",
      "#PeacefulMind",
      "#ProudMoment",
    ],
  },
  {
    id: 17,
    letter: "Q",
    hashtags: [
      "#QualityOverQuantity",
      "#QuietConfidence",
      "#QuestForMore",
      "#QuickSuccess",
      "#QuestionEverything",
      "#QuotableMoments",
      "#QuantumLeap",
      "#QuietStrength",
      "#QualityLife",
      "#QuenchYourThirst",
    ],
  },
  {
    id: 18,
    letter: "R",
    hashtags: [
      "#RiseAndShine",
      "#Resilience",
      "#Relaxation",
      "#Revolution",
      "#Respect",
      "#RebootYourLife",
      "#ReachingNewHeights",
      "#ResultsDriven",
      "#Reflection",
      "#Reignite",
    ],
  },
  {
    id: 19,
    letter: "S",
    hashtags: [
      "#Success",
      "#Strength",
      "#SelfLove",
      "#Sustainable",
      "#SmileMore",
      "#SupportEachOther",
      "#SoulPurpose",
      "#StandOut",
      "#Superstar",
      "#StartStrong",
    ],
  },
  {
    id: 20,
    letter: "T",
    hashtags: [
      "#Transformation",
      "#Teamwork",
      "#Thankful",
      "#TrueToYourself",
      "#TakeAction",
      "#ThinkBig",
      "#TrustTheProcess",
      "#ToughTimes",
      "#Thrive",
      "#TackleYourGoals",
    ],
  },
  {
    id: 21,
    letter: "U",
    hashtags: [
      "#Unstoppable",
      "#Unique",
      "#UltimateGoal",
      "#UnlimitedPotential",
      "#UnderstandYourWorth",
      "#Uplift",
      "#UnleashYourPower",
      "#UnderdogStory",
      "#UnlockTheFuture",
      "#UnitedWeStand",
    ],
  },
  {
    id: 22,
    letter: "V",
    hashtags: [
      "#Victory",
      "#Vibes",
      "#Visionary",
      "#VibrantLife",
      "#Valuable",
      "#Virtue",
      "#Venture",
      "#VocalForChange",
      "#Vitality",
      "#VowToWin",
    ],
  },
  {
    id: 23,
    letter: "W",
    hashtags: [
      "#Wanderlust",
      "#WinningMindset",
      "#WeAreOne",
      "#WellnessJourney",
      "#Worthy",
      "#WorkHardPlayHard",
      "#WakeUpAndWin",
      "#Woke",
      "#Wonderful",
      "#WorldChanger",
    ],
  },
  {
    id: 24,
    letter: "X",
    hashtags: [
      "#Xtraordinary",
      "#Xploration",
      "#Xcellence",
      "#XperienceLife",
      "#XtraEffort",
      "#XploreMore",
      "#Xclusive",
      "#Xenial",
      "#XenonEnergy",
      "#XpectSuccess",
    ],
  },
  {
    id: 25,
    letter: "Y",
    hashtags: [
      "#YouGotThis",
      "#YesYouCan",
      "#YoungAtHeart",
      "#YearOfGrowth",
      "#YouAreEnough",
      "#Yolo",
      "#YourTimeIsNow",
      "#YieldSuccess",
      "#YogaLife",
      "#YourJourney",
    ],
  },
  {
    id: 26,
    letter: "Z",
    hashtags: [
      "#Zen",
      "#ZestForLife",
      "#ZeroLimits",
      "#ZodiacVibes",
      "#ZoomInOnSuccess",
      "#ZigZagPath",
      "#Zinger",
      "#Zestful",
      "#ZippingAhead",
      "#ZillionDreams",
    ],
  },
];

export default hashtagsAPI;
